### ISSUE TITLE
Styling line numbers not working

### ISSUE THREAD

**Issue by ghost** [Aweary/gist.scss#1]
Hi, first of all, I really like your solution to style the embedded Gists. Unfortunately, and I'm not sure if you be aware of this, but the script is not working like it should be. Styling the background, colors, padding and borders works fine. The styling of the line numbers does not work. Is this because Github changed there own stylesheet recently?

**Comment by aweary** [comment]
Hey Ron, thanks for opening an issue. The classes may have changed since I last updated this repository. You can try inspecting the line number elements and seeing if they're using a class I didn't add yet.

**Comment by ghost** [comment]
That was my second suggestion. I see that there are some new classes indeed.  I added a few classes to your mixins and now it is working fine.

Thnx so far and keep up the good work.

By the way, do you have plans to update your repo?

**Comment by aweary** [comment]
I definitely do. If you found a class that needs to be added or an update that needs to be made, feel free to open a pull request! Or if you don't want to, just let me know what you updated :smile:
